# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\07_ComboBoxes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb1 = QtWidgets.QComboBox(self.centralwidget)
        self.cb1.setGeometry(QtCore.QRect(100, 120, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cb1.setFont(font)
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb2 = QtWidgets.QComboBox(self.centralwidget)
        self.cb2.setGeometry(QtCore.QRect(410, 120, 81, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.cb2.setFont(font)
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("")
        self.cb2.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 531, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 330, 411, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 230, 231, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # add item to the combo box
        '''
        self.cb1.addItem("Hello")
        index= self.cb1.findText("Hello", QtCore.Qt.MatchFixedString)
        self.cb1.setCurrentIndex(index)
        '''

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.pressed)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb1.setItemText(0, _translate("MainWindow", "0"))
        self.cb1.setItemText(1, _translate("MainWindow", "1"))
        self.cb2.setItemText(0, _translate("MainWindow", "0"))
        self.cb2.setItemText(1, _translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "XOR Machine"))
        self.label_2.setText(_translate("MainWindow", "0 XOR 0 = 0"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))

    def pressed(self):
        # print(self.cb1.currentText())
        # print(self.cb2.currentText())

        x= int(self.cb1.currentText())
        y= int(self.cb2.currentText())
        xor= x^y
        xor= 1 if xor else 0
        self.label_2.setText(f"{x} XOR {y} = {xor}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
